"""
STIGMERGY — Audit Chain
========================
Per-node, tamper-evident hash chain (Invariants 3 and 5, ARCHITECTURE.md).

Invariant 3: no committed state transition may exist without a
corresponding audit event, written in the SAME transaction as the state
change it explains. This module never opens or commits a transaction on
its own for the write path — the caller passes in an open cursor that is
already inside their transaction, and record_event() adds one more
statement to it. Because CockroachDB is transactional across tables,
there is no separate CRONOS-style "seal" step: the whole transaction
commits atomically, or none of it does. If the audit write fails, the
state change it was meant to explain is rolled back with it — by
construction, not by convention.

Invariant 5: audit_chain is per-node. Global ordering across nodes is
never assumed. Cross-node integrity is established separately, via the
chained Merkle ledger in merkle_snapshots (see merkle.py).

Node identity
-------------
node_id is never something a human is expected to remember. It is
derived automatically once per machine and persisted to
~/.stigmergy/node_id. An optional STIGMERGY_NODE_ID environment variable
can override it — useful for giving nodes human-readable labels in a
demo — but nothing breaks if it is absent.

record_event() deliberately does NOT accept node_id as a parameter. It
always writes to the LOCAL node's chain via get_node_id() internally.
This is an identity guarantee, not an inconvenience: no caller, buggy or
malicious, can write an audit event into another node's chain. Tests
that need to simulate multiple nodes should set STIGMERGY_NODE_ID before
each call, not pass node_id directly. verify_chain(), being a read-only
audit operation, keeps node_id as an explicit parameter — it must be
able to check the chain of ANY node (the periodic Merkle snapshot job
needs to read every node's chain head, not just the local one).
"""

from __future__ import annotations

import datetime
import decimal
import hashlib
import json
import os
import re
import uuid
from pathlib import Path
from typing import Any

# -----------------------------------------------------------------------------
# Node identity — autogenerated, persisted, never manually required.
# -----------------------------------------------------------------------------

_NODE_ID_DIR = Path.home() / ".stigmergy"
_NODE_ID_FILE = _NODE_ID_DIR / "node_id"

_MAX_NODE_ID_LEN = 64
_NODE_ID_PATTERN = re.compile(r"^[a-zA-Z0-9_-]+$")


def get_node_id() -> str:
    """
    Return this machine's stable node_id.

    Resolution order:
      1. STIGMERGY_NODE_ID environment variable, if set (demo labeling).
         Validated: alphanumeric plus hyphen/underscore, max 64 chars.
         node_id is a PRIMARY KEY component in audit_chain — an
         unbounded or adversarial value here is a real footgun, not
         just an oddity.
      2. Previously persisted id at ~/.stigmergy/node_id.
      3. Freshly generated id, persisted for all future runs.
    """
    env_override = os.environ.get("STIGMERGY_NODE_ID", "").strip()
    if env_override:
        if len(env_override) > _MAX_NODE_ID_LEN:
            raise ValueError(
                f"STIGMERGY_NODE_ID too long ({len(env_override)} chars, "
                f"max {_MAX_NODE_ID_LEN})."
            )
        if not _NODE_ID_PATTERN.match(env_override):
            raise ValueError(
                "STIGMERGY_NODE_ID must contain only letters, digits, "
                "hyphens, and underscores."
            )
        return env_override

    if _NODE_ID_FILE.exists():
        existing = _NODE_ID_FILE.read_text(encoding="utf-8").strip()
        if existing:
            return existing

    _NODE_ID_DIR.mkdir(parents=True, exist_ok=True)
    new_id = f"node-{uuid.uuid4().hex[:12]}"
    _NODE_ID_FILE.write_text(new_id, encoding="utf-8")
    return new_id


# -----------------------------------------------------------------------------
# Genesis — a documented constant, never an empty string or NULL.
#
# Deliberately shared across all nodes, not derived per-node. This is not
# a weakness: node_id is already part of every entry's hash starting at
# seq=0, so two nodes' chains diverge immediately regardless of a shared
# genesis constant. The constant exists to avoid the ambiguity of NULL
# or "" as a "no previous entry" marker — it was never meant to act as a
# secret cryptographic seed, so deriving it per-node would add a layer
# without a corresponding security benefit.
# -----------------------------------------------------------------------------

GENESIS_SEED = "STIGMERGY_GENESIS"
GENESIS_HASH = hashlib.sha256(GENESIS_SEED.encode("utf-8")).hexdigest()


class ChainWriteConflict(Exception):
    """
    Raised when a concurrent writer on the same node_id raced this call
    to append the next chain entry (both read the same prev_hash/seq
    before either inserted). This is an EXPECTED condition under
    CockroachDB's serializable isolation when two processes on the same
    machine write concurrently — it is not corruption.

    The caller MUST retry the entire transaction from the top (the
    state-changing write included, not just this call), so a fresh
    seq/prev_hash is read after the race resolves.
    """


# -----------------------------------------------------------------------------
# Canonical serialization — same discipline as VIGÍA's canonicalize.py.
# Sorted keys, no whitespace ambiguity, explicit handling of the only
# non-JSON-native types this project actually passes in payloads. Any
# other type is a bug at the call site, not something to paper over with
# str() — silently stringifying arbitrary objects is how determinism
# quietly breaks across platforms or library versions.
# -----------------------------------------------------------------------------

def _json_default(obj: Any) -> Any:
    if isinstance(obj, (datetime.datetime, datetime.date)):
        return obj.isoformat()
    if isinstance(obj, decimal.Decimal):
        return str(obj.normalize())
    raise TypeError(
        f"Object of type {type(obj).__name__} is not canonically "
        f"serializable in an audit payload. Convert it explicitly "
        f"before calling record_event()."
    )


def _canonical_json(payload: dict[str, Any]) -> str:
    return json.dumps(
        payload, sort_keys=True, separators=(",", ":"), default=_json_default
    )


def _compute_entry_hash(
    prev_hash: str,
    node_id: str,
    seq: int,
    event_type: str,
    reason: str,
    canonical_payload: str,
) -> str:
    """
    canonical_payload is expected to already be the output of
    _canonical_json() — computed once by the caller and reused for both
    the hash and the stored payload_json, so the two never diverge.

    Fields are joined via JSON array serialization, not string
    concatenation with a plain delimiter. A delimiter like "|" is
    ambiguous if it can appear inside a field (e.g. event_type="A|B",
    reason="C" hashes identically to event_type="A", reason="B|C").
    JSON's own escaping makes this unambiguous regardless of content.
    """
    raw = json.dumps(
        [prev_hash, node_id, seq, event_type, reason, canonical_payload],
        separators=(",", ":"),
    )
    return hashlib.sha256(raw.encode("utf-8")).hexdigest()


# -----------------------------------------------------------------------------
# Write path
# -----------------------------------------------------------------------------

def record_event(
    cursor,
    event_type: str,
    reason: str,
    payload: dict[str, Any],
) -> tuple[int, str]:
    """
    Append one event to the LOCAL node's audit chain (see module
    docstring for why node_id is never a parameter here).

    MUST be called with a cursor that is inside the SAME transaction as
    the state-changing write this event explains (Invariant 3). Does
    NOT commit — the caller commits once, after both writes have been
    issued, so the state change and its audit record land together or
    not at all.

    Raises ChainWriteConflict if a concurrent writer on this node raced
    this call — the caller must retry the whole transaction, not just
    this function.

    Returns (seq, entry_hash) of the newly written entry.
    """
    if not event_type or not event_type.strip():
        raise ValueError("event_type is required and cannot be empty.")
    if not reason or not reason.strip():
        raise ValueError(
            "reason is required and cannot be empty — an audit event "
            "without a stated reason cannot exist (Invariant 3)."
        )
    if not isinstance(payload, dict):
        raise TypeError(
            f"payload must be a dict — got {type(payload).__name__}. "
            "The audit trail is structured data, not free text."
        )

    node_id = get_node_id()

    # FOR UPDATE is required, not optional. Without it, two concurrent
    # writers on this node could both read the same (seq, entry_hash)
    # before either inserts, and both would compute the same next seq —
    # a local fork. Do not "simplify" this away; see ChainWriteConflict
    # below for what happens on the rare occasion it still races.
    cursor.execute(
        """
        SELECT seq, entry_hash FROM audit_chain
        WHERE node_id = %s
        ORDER BY seq DESC
        LIMIT 1
        FOR UPDATE
        """,
        (node_id,),
    )
    row = cursor.fetchone()

    if row is None:
        seq = 0
        prev_hash = GENESIS_HASH
    else:
        last_seq, last_entry_hash = row
        seq = last_seq + 1
        prev_hash = last_entry_hash

    canonical_payload = _canonical_json(payload)
    entry_hash = _compute_entry_hash(
        prev_hash, node_id, seq, event_type, reason, canonical_payload
    )

    try:
        cursor.execute(
            """
            INSERT INTO audit_chain
                (node_id, seq, prev_hash, entry_hash, event_type, reason, payload_json)
            VALUES (%s, %s, %s, %s, %s, %s, %s)
            """,
            (node_id, seq, prev_hash, entry_hash, event_type, reason, canonical_payload),
        )
    except Exception as exc:
        sqlstate = getattr(exc, "sqlstate", None)
        if sqlstate is None:
            diag = getattr(exc, "diag", None)
            sqlstate = getattr(diag, "sqlstate", None)
        if sqlstate == "23505":  # unique_violation
            raise ChainWriteConflict(
                f"Concurrent write race on node {node_id!r} at seq={seq}. "
                "Retry the entire transaction, not just this call."
            ) from exc
        raise

    return seq, entry_hash


# -----------------------------------------------------------------------------
# Verify path
# -----------------------------------------------------------------------------

def _coerce_payload(payload_json: Any, seq: int, errors: list[str]) -> dict[str, Any] | None:
    """
    Normalize whatever the driver handed back for a JSONB column into a
    dict, without ever raising — a corrupted or unexpectedly-typed
    payload must be REPORTED by verify_chain, not crash it.
    """
    if isinstance(payload_json, dict):
        return payload_json
    if isinstance(payload_json, (bytes, memoryview)):
        payload_json = bytes(payload_json).decode("utf-8", errors="replace")
    if isinstance(payload_json, str):
        try:
            return json.loads(payload_json)
        except json.JSONDecodeError as exc:
            errors.append(f"seq {seq}: payload_json is not valid JSON: {exc}")
            return None
    errors.append(
        f"seq {seq}: payload_json has unexpected type {type(payload_json).__name__}."
    )
    return None


def verify_chain(cursor, node_id: str) -> tuple[bool, list[str]]:
    """
    Recompute every hash in the given node's chain and check linkage.

    Any retroactive modification of any entry — payload, reason,
    event_type, or a deleted/reordered row — breaks every subsequent
    hash. Returns (chain_ok, errors). An empty chain is valid (chain_ok
    is True, errors is empty) — a node that has recorded nothing has not
    been tampered with.

    node_id is explicit here (unlike record_event) because this is a
    read-only audit operation that must be able to check ANY node's
    chain, not just the local one — the Merkle snapshot job depends on
    this.
    """
    cursor.execute(
        """
        SELECT seq, prev_hash, entry_hash, event_type, reason, payload_json
        FROM audit_chain
        WHERE node_id = %s
        ORDER BY seq ASC
        """,
        (node_id,),
    )
    rows = cursor.fetchall()

    errors: list[str] = []
    expected_prev = GENESIS_HASH
    expected_seq = 0

    for seq, prev_hash, entry_hash, event_type, reason, payload_json in rows:
        if seq != expected_seq:
            errors.append(
                f"seq gap or duplicate: expected {expected_seq}, found {seq}."
            )
        if prev_hash != expected_prev:
            errors.append(
                f"seq {seq}: prev_hash does not match the previous entry's "
                f"entry_hash — chain link broken."
            )

        payload = _coerce_payload(payload_json, seq, errors)
        if payload is not None:
            canonical_payload = _canonical_json(payload)
            recomputed = _compute_entry_hash(
                prev_hash, node_id, seq, event_type, reason, canonical_payload
            )
            if recomputed != entry_hash:
                errors.append(
                    f"seq {seq}: entry_hash does not match recomputed value — "
                    f"payload, reason, or event_type was altered after the fact."
                )

        expected_prev = entry_hash
        expected_seq = seq + 1

    return (len(errors) == 0, errors)
